/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\forest-house.glb -T 
Files: .\forest-house.glb [8.56MB] > Z:\Next\ReactDeveloperPortfolio\public\models\forest-house-transformed.glb [679.5KB] (92%)
Author: peachyroyalty (https://sketchfab.com/peachyroyalty)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/forest-house-52429e4ef7bf4deda1309364a2cda86f
Title: Forest House
*/

'use client'

import React from 'react'
import {useGLTF} from '@react-three/drei'
import * as THREE from "three";
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Windows001_Window_0: THREE.Mesh;
    SideRoofBase_RoofMoss_0: THREE.Mesh;
    HouseFence_WoodPlanks_0: THREE.Mesh;
    House_House_0: THREE.Mesh;
    TallGrass_GrassALPHA_0: THREE.Mesh;
    FenceRight_WoodFence_0: THREE.Mesh;
    SmallRocks_BigRock_0: THREE.Mesh;
    BTree001_BrichTree_0: THREE.Mesh;
    RedwoodAlpha_TreeLeafs_0: THREE.Mesh;
    Ground_Ground_0: THREE.Mesh;
    Racoon_Animals_0: THREE.Mesh;
    GroundPlane_Plane_0: THREE.Mesh;
  };
  materials: {
    Window: THREE.MeshStandardMaterial;
    RoofMoss: THREE.MeshStandardMaterial;
    WoodPlanks: THREE.MeshStandardMaterial;
    House: THREE.MeshStandardMaterial;
    GrassALPHA: THREE.MeshStandardMaterial;
    WoodFence: THREE.MeshStandardMaterial;
    BigRock: THREE.MeshStandardMaterial;
    BrichTree: THREE.MeshStandardMaterial;
    TreeLeafs: THREE.MeshStandardMaterial;
    Ground: THREE.MeshStandardMaterial;
    Animals: THREE.MeshStandardMaterial;
    Plane: THREE.MeshStandardMaterial;
  };
};

type ForestHouseProps = {
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number | [number, number, number];
  [key: string]: any;
};



export function ForestHouse(props: ForestHouseProps) {
    const {nodes, materials} = useGLTF('/models/forest-house-transformed.glb') as unknown as GLTFResult

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Windows001_Window_0.geometry} material={materials.Window}
                  position={[-0.004, 0.026, -0.024]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.SideRoofBase_RoofMoss_0.geometry} material={materials.RoofMoss}
                  position={[-0.013, 0.033, -0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.HouseFence_WoodPlanks_0.geometry} material={materials.WoodPlanks}
                  position={[-0.033, 0.02, -0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.House_House_0.geometry} material={materials.House} position={[-0.017, 0.037, -0.007]}
                  rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.TallGrass_GrassALPHA_0.geometry} material={materials.GrassALPHA}
                  position={[-0.032, 0.018, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.FenceRight_WoodFence_0.geometry} material={materials.WoodFence}
                  position={[-0.048, 0.013, 0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.SmallRocks_BigRock_0.geometry} material={materials.BigRock}
                  position={[0.001, 0.018, -0.031]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.BTree001_BrichTree_0.geometry} material={materials.BrichTree}
                  position={[-0.028, 0.073, -0.039]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.RedwoodAlpha_TreeLeafs_0.geometry} material={materials.TreeLeafs}
                  position={[-0.012, 0.082, -0.014]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.Ground_Ground_0.geometry} material={materials.Ground}
                  position={[-0.032, 0.013, -0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.Racoon_Animals_0.geometry} material={materials.Animals}
                  position={[-0.04, 0.018, -0.04]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
            <mesh geometry={nodes.GroundPlane_Plane_0.geometry} material={materials.Plane}
                  position={[-0.03, 0.008, -0.011]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014}/>
        </group>
    )
}

useGLTF.preload('/models/forest-house-transformed.glb')
