/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\supabase.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Supabase(props) {
  const { nodes, materials } = useGLTF('/models/supabase.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} />
    </group>
  )
}

useGLTF.preload('/models/supabase.glb')
